apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: default
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.27.0
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
            - "--storage.path=/alertmanager"
          ports:
            - containerPort: 9093
              name: web
          env:
            - name: SMTP_SMARTHOST
              valueFrom:
                secretKeyRef:
                  name: alertmanager-smtp
                  key: smtp_smarthost
            - name: SMTP_FROM
              valueFrom:
                secretKeyRef:
                  name: alertmanager-smtp
                  key: smtp_from
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: alertmanager-smtp
                  key: smtp_username
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: alertmanager-smtp
                  key: smtp_password
          volumeMounts:
            - name: alertmanager-config
              mountPath: /etc/alertmanager/alertmanager.yml
              subPath: alertmanager.yml
            - name: alertmanager-storage
              mountPath: /alertmanager
      volumes:
        - name: alertmanager-config
          configMap:
            name: alertmanager-config
            items:
              - key: alertmanager.yml
                path: alertmanager.yml
        - name: alertmanager-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: default
  labels:
    app: alertmanager
spec:
  type: ClusterIP
  selector:
    app: alertmanager
  ports:
    - name: web
      port: 9093
      targetPort: web
