apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: default
  labels:
    app: alertmanager
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: '${SMTP_SMARTHOST}'
      smtp_from: '${SMTP_FROM}'
      smtp_auth_username: '${SMTP_USERNAME}'
      smtp_auth_password: '${SMTP_PASSWORD}'
      smtp_require_tls: true
    route:
      receiver: email-notifications
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
    receivers:
      - name: email-notifications
        email_configs:
          - to: '${SMTP_TO}'
            send_resolved: true
